stages:
  - build
  - test
  - package
  - docker_build
  - deploy

variables:
  DOCKER_IMAGE: hotmanamrani/test-app
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

image: docker:24.0.0
services:
  - name: docker:24.0.0-dind
    command: ["--tls=false"]

build:
  stage: build
  image: maven:3.8.4-openjdk-11
  script:
    - mvn clean

test:
  stage: test
  image: maven:3.8.4-openjdk-11
  script:
    - mvn test

package:
  stage: package
  image: maven:3.8.4-openjdk-11
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar

docker_build:
  stage: docker_build
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest



deploy:
  stage: deploy
  script:
    - kubectl apply -f deployment.yml
  environment:
    name: production
    url: http://192.168.2.49:8080